language: python
python:
  - 3.5

services:
  - docker

install:
  - docker build \
    -t crossbario/autobahn-java:netty \
    -f ./docker/Dockerfile.netty \
    .

script:
  - docker run --rm \
      -p 8080:8080 --name crossbar \
      crossbario/crossbar

  - docker run --rm \
      --link crossbar \
      -v ${PWD}/test_component.py:/test_component.py  \
      crossbario/autobahn-python \
      python -u /test_component.py

  - docker run --rm -it \
      --link crossbar \
      -v ${shell pwd}:/workspace \
      crossbario/autobahn-java:netty \
      /bin/bash -c "demo-gallery/build/install/demo-gallery/bin/demo-gallery ws://crossbar:8080/ws"
